### ISSUE TITLE
When is the 3.0.0 coming out?

### ISSUE THREAD

**Issue by sarukuku** [Automattic/regenerate-thumbnails#26]
Just wondering. People are starting to upgrade to PHP 7.0 and are probably seeing at least the alert of the constructor.

```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; RegenerateThumbnails has a deprecated constructor in /srv/www/scala.bondsrv.com/public/wp-content/plugins/regenerate-thumbnails/regenerate-thumbnails.php on line 32
```

**Comment by Viper007Bond** [comment]
I've been making very slow progress, partially due to feature bloat, but maybe I'll trim some of that stuff back for a future version. I still want to finish rewriting it for 3.0.0 though.

Meanwhile I'll push out a 2.x version with a quick fix for that.

However aren't deprecated warnings normally off on a production server? They're more an error message meant for development servers.

**Comment by sarukuku** [comment]
Sounds good and Yes they are. Just wanted to give you a heads up. :)

**Comment by Viper007Bond** [comment]
https://plugins.trac.wordpress.org/changeset/1318415/regenerate-thumbnails

**Comment by sarukuku** [comment]
Thanks man :+1:
