### ISSUE TITLE
Gutenberg compatibility: "Regenerate" link for Featured image section

### ISSUE THREAD

**Issue by lkraav** [Automattic/regenerate-thumbnails#53]
Not sure if too early to file this, but sure would be nice to have. With the new REST API infrastructure in place, perhaps possible now?

**Comment by Viper007Bond** [comment]
I'm assuming you're talking about adding a button to the "Featured Image" widget/module? I'm not sure it's worth adding UI bloat to Gutenberg in the form of an additional button, especially since it'll rarely be used (only when changing themes or image sizes).

Additionally the plugin can regenerate just featured images, and you can also click on the featured image to open the media dialog. You can then click on any of the images, including the one that's selected as a featured image, and there will be a regenerate button in the bottom right.

**Comment by lkraav** [comment]
Indeed, regenerating from inside Media modal works as well.

One UX issue I'm seeing is that when clicking on featured image in Gutenberg, the currently set featured image is not pre-selected in Media modal - nothing is. It feels like the current featured image should be pre-selected and auto-scrolled into view. This may have contributed to my confusion of thinking the regenerate process is complicated. Are you seeing the same thing?

**Comment by Viper007Bond** [comment]
I'm seeing the same thing and I think it's because the modal is designed for you to be picking a new featured image. Pre-selecting the current image might be useful -- maybe worth opening a core ticket.
