### ISSUE TITLE
Causes Media Manager To Run Slowly

### ISSUE THREAD

**Issue by charpun** [Automattic/regenerate-thumbnails#63]
Causes media manager AJAX to timeout or run super slowly when dealing with a large number of PDFs.

**Comment by Viper007Bond** [comment]
This should be fixed by https://github.com/Viper007Bond/regenerate-thumbnails/commit/fffbe23c6633ac7760e58fbe9b74a1ad95b40426 which will be included in the next release.

Can you [download the latest development version](https://raw.githubusercontent.com/Viper007Bond/regenerate-thumbnails/master/regenerate-thumbnails.php) and confirm that it fixes the issue?

**Comment by Viper007Bond** [comment]
#61
