### ISSUE TITLE
Regenerate Thumbnails doesn't work

### ISSUE THREAD

**Issue by stfler90** [Automattic/regenerate-thumbnails#68]
Hi, Alex. I'm using your plugin for 5 month. Evething was great! But since today it doesn't work and shows me a mistake: This tool won't be able to do anything because your server doesn't support image editing which means that WordPress can't create thumbnail images. Please ask your host to install the Imagick or GD PHP extensions.

But imagick is installed on the server. And i tried to switch to the GD PHP and it also doesn't work.;(

Thanks in advanse for your answer!

**Comment by Viper007Bond** [comment]
Try installing the Health Check plugin: https://wordpress.org/plugins/health-check/

Then go to Dashboard → Health Check → "Debug information" tab → "Media handling" subsection. It'll tell you what WordPress image editor is being used and if you have ImageMagic correctly installed.

**Comment by stfler90** [comment]
Thanks, Alex for your advise! I installed Health Check plugin, it shown that Imagick and GD PHP didn’t work really. Then i wrote my Host Support, they fixed the bug (they added one more time my account to CageFS). So now your plugin works great as always!

**Comment by DDvirgoman** [comment]
when I try to use the plugin Regenerate Thumbnails. I received a message "This tool won't be able to do anything because your server doesn't support image editing which means that WordPress can't create a thumbnail image ask your host to install the Imagick or GD PHP extensions" and I contact my hosting "hostinger.in.th" and they confirmed that on a server has the Imagick or GD PHP extensions.    Can you help me with this issue?

**Comment by md-shuvoislam** [comment]
I got the same issue with my local host. how can I fix that?

**Comment by DrIanGregory** [comment]
I can confirm the following commands on Ubuntu 20.04 FIXES the issue:

sudo apt-get install -y php-gd
sudo systemctl restart apache2

"Refresh WordPress in web browser".
